### PR TITLE
Added hardware directory structure

### PR DESCRIPTION
**Pull request by PrabhanshuAttri**
#43

### CODE REVIEW

**Comment by ab7289** [comment]
Should we be PR'ing this directly into Master @PrabhanshuAttri ?

**Review by ab7289 — CHANGES_REQUESTED** [review]
We should be PR'ing this into develop before master

**Comment by PrabhanshuAttri** [comment]
I have switched the base to develop. Thanks for pointing this out

**Review by ab7289 — COMMENTED** [review]
LGTM!

**Review by ab7289 — APPROVED** [review]

**Comment by ab7289** [comment]
Approved! Feel free to merge at your convenience.

Alex Biehl
Application Analyst/Developer
NYU
Desk: 212 992 6784
email: alex.biehl@nyu.edu <ab7289@nyu.edu>

**Pull request merged**
